### PR TITLE
Resolve symlink to composer shell executable.

### PR DESCRIPTION
**Pull request by r3c**
Shell entry point for Composer used to resolve self-relative `composer.phar` file. However current code didn't handle symlinked `composer` file (e.g. useful when not adding `composer` to `$PATH`) and assumed `composer.phar` always shared symlink's base directory instead of target's one.

This PR adds missing symlink normalization using `readlink` to workaround this limitation.

### CODE REVIEW

**Comment by johnstevenson** [comment]
> However current code didn't handle symlinked composer file

Thanks, but there is no need for this because ComposerSetup explicitly puts the composer files (phar and shims) on the PATH.

**Comment by r3c** [comment]
> Thanks, but there is no need for this because ComposerSetup explicitly puts the composer files (phar and shims) on the PATH.

Indeed it does, but this approach precisely doesn't work when creating a symlink to composer because current Shell code resolves the directory of the symlink rather than its target.

**Comment by johnstevenson** [comment]
> but this approach precisely doesn't work when creating a symlink to composer...

Of course, so just add your modification locally.

**Comment by r3c** [comment]
> Of course, so just add your modification locally.

That's what I'm doing so far. I was proposing this PR to unlock the feature for other users, as it doesn't restrict anything compared to current resolution approach.

**Pull request closed without merging**
